#!/bin/sh

choice=$(sxiv -t -r -q -o $HOME/multimedia/pictures)
cp $choice $HOME/.config/wallpaper.jpg
xwallpaper --zoom $HOME/.config/wallpaper.jpg
notify-send -i $HOME/.config/wallpaper.jpg "Is your new wallpaper!" && exit 1
